---
- hosts: all
  become: yes
  tags: deploy
  
  tasks:
    - name: Запустить Redmine в контейнере
      community.docker.docker_container:
        image: redmine: "{{ app_tag }}"
        platform: linux/amd64
        name: redmine
        state: started
        restart: true
        ports:
          - "{{ app_port }}:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ redmine_db_postgres }}"
          REDMINE_DB_USERNAME: "{{ redmine_db_username }}"
          REDMINE_DB_PASSWORD: "{{ redmine_db_password }}"
          REDMINE_DB_PORT: "{{ redmine_db_port }}"
          REDMINE_DB_DATABASE: "{{ redmine_db_database }}"
      become: true
       

- hosts: webservers
  roles:
    - { role: datadog.datadog, become: yes }
  tags: datadog
