---
- hosts: all
  become: yes
  tags: deploy
  vars_files:
    - ./group_vars/webservers/common.yml
  tasks:
    - name: Запустить Redmine в контейнере
      docker_container:
        name: redmine
        image: redmine:latest
        ports:
          - "80:3000"
        
        state: started

- hosts: webservers
  roles:
    - { role: datadog.datadog, become: yes, datadog_config_file: "/group_vars/webservers/datadog.yml" }
  tags: datadog


