---
- hosts: all
  become: yes
  tags: deploy
  tasks:
    - name: Запустить Redmine в контейнере
      docker_container:
        name: redmine
        image: redmine
        state: started
        restart_policy: always
        ports:
          - "80:3000"
        env:
          PSQL_HOST: "{{ vault_redmine_db_postgres }}"
          PSQL_PORT: "{{ vault_redmine_db_ports }}"
          PSQL_SSLMODE: "{{ vault_redmine_db_sslmode }}"
          PSQL_DBNAME: "{{ vault_redmine_db_database }}"
          PSQL_USER: "{{ vault_redmine_db_username }}"
          PSQL_TARGET_SESSION_ATTRS: "{{ vault_redmine_target }}"
       

- hosts: webservers
  roles:
    - { role: datadog.datadog, become: yes }
  tags: datadog


