datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_checks:
  http_check:
    instances:
      - name: http_check_{{ inventory_hostname }}
        url: http://localhost:3000
        timeout: 15
        min_collection_interval: 30   